name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn --batch-mode clean verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-demo:latest

      - name: Deploy Application
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-demo:latest

          docker stop java-devops-demo || true
          docker rm java-devops-demo || true

          docker run -d \
            --name java-devops-demo \
            -p 8080:8080 \
            ${{ secrets.DOCKERHUB_USERNAME }}/java-devops-demo:latest
